#!/usr/bin/env python3
'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
s=0
f1=1
f2=1
while True:
    f3=f1+f2
    #print(f3)
    if f3>4000000:
        break;
    if f3%2==0:
        s+=f3
    f1=f2
    f2=f3

print(s)
