#!/usr/bin/env python3
'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

What is the value of the first triangle number to have over five hundred divisors?
'''
import math
n=1
while True:
    n+=1
    t=int(n*(n+1)/2)
    #Only count multiples of 2*3*5
    if t%(2*3*5)==0:
        dcount=0
        for i in range(1,int(math.sqrt(t))+1):
            if t%i==0:
                dcount+=2
        #print(n,t,dcount)
        if dcount>500:
            print(t)
            break
